### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghost**
First successful test of opensearch for openEO

### CODE REVIEW

**Comment by m-mohr** [comment]
Thanks for your submission @prateekbudhwar . I think it makes more sense to add the actual content of the zip file instead of the zip file itself. Would you mind changing the PR accordingly?

**Comment by m-mohr** [comment]
Thanks! There is still the ZIP file in the PR, which is not suitable for versioning. Could you remove it, please?

**Comment by ghost** [comment]
@m-mohr I can't find the zip file now. Did u remove it already ?

**Comment by m-mohr** [comment]
No, I didn't... I may just merge and remove it again. ;)

**Comment by GreatEmerald** [comment]
That's not a good idea... If you don't squash the commit, the zip file will stay there forever, unless you rewrite history!

**Comment by GreatEmerald** [comment]
See: https://help.github.com/articles/removing-files-from-a-repository-s-history/
Removing a binary file from a repository just hides it, you still need to download it every time when cloning... And rewriting history means that all forks need to refork, else they see doubled commits. It's real messy if you put binary files into git...

**Comment by ghost** [comment]
Ooops.. sry for that to everyone..

**Pull request merged**
